config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  get 'pages/portfolio' => 'pages#portfolio'
  get 'pages/about' => 'pages#about'

  resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,        :validate => true
    attribute :email,       :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,     :validate => true
    attribute :nickname,    :captcha => true
    
    def headers 
        {
            :subject => "Contact Form",
            :to => "andrea.maffia3@gmail.como",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = 'Cannot send message.'
            render :new
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def welcome
    end

    def portfolio
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h1 id="page-title">Mafrend</h1>

<div class="wrapper">
    <h1>Thank you for your message!</h1>
    <p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page-title">Contact me</h1>

<div class="contact-container">
    <div class="contact-wrapper">
        <div class="contact-form">
            <%= form_for @contact do |f| %>
                <div class="label-name">
                    <%= f.label :name %><br>
                    <%= f.text_field :name, required: true, class:"label-name-area" %>
                </div>

                <br>

                <div class="label-email">
                    <%= f.label :email %><br>
                    <%= f.email_field :email, required: true, class:"email-area" %>
                </div>

                <br>

                <div class="label-message">
                    <%= f.label :message %><br>
                    <%= f.text_area :message, as: :text, class:"message-area" %>
                </div>

                <%= f.submit 'Send it!', class:"send-button" %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    
    <!-- Fonts -->
    <!-- Roboto -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet">

    <!-- Roboto Mono -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">    
    
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/fea2143243.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <!-- BulmaCSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'pages/header' %>
    <%= yield %>
    <%= render 'pages/footer' %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer>
    <div class="inner-footer">
        <div class="footer-third">
            <li><a href="https://github.com/andreamaf01"><i class="fab fa-github fa-2x"></i></a></li>
            <li><a href="https://www.linkedin.com/in/maffia-andrea-087011156/"><i class="fab fa-linkedin fa-2x"></i></a></li>
            <li><a href="https://twitter.com/andreamaffia3"><i class="fab fa-twitter fa-2x"></i></a></li>
        </div>

        <div class="copyright">
            <p> &copy; 2021 Andrea Maffia </p>
        </div> 
    </div>
</footer>

app/views/pages/_header.html.erb
<div class="header sticky-top">
    <div class="nav-bar">
        <%= link_to 'Welcome', root_path, class:"header-link" %>
        <%= link_to 'Portfolio', pages_portfolio_path, class:"header-link" %>
        <%= link_to 'About', pages_about_path, class:"header-link" %>
        <%= link_to 'Contact', new_contact_path, class:"header-link" %>
    </div>
</div>

app/views/pages/about.html.erb
<div class="about-container">
    <div class="about-image-container">
        <%= image_tag "about-image.jpg", class:"about-image-style", alt:"Andrea's profile pic" %>
    </div>

    <div class="about-text">
        <p>Born in 1995 in Senigallia, a small town on the east side of Italy, facing the Adriatic Sea.</p>
        <br> 
        <p>I have studied Political Sciences and International Relations at the University of Macerata.</p>
        <br> 
        <p>I have always been fascinated by coding so I am learning web development, in particular html, CSS, Ruby, Ruby on Rails and Javascript.</p>
        <br>
    </div>
</div>

app/views/pages/portfolio.html.erb
<main>
    <div class="container">
        <div class="image-container">
            <%= image_tag "work-in-progress-paint1.png", class:"image-style", alt:"Work in Progress" %>
        </div>
    </div>
</main>

app/views/pages/welcome.html.erb
<div class="main">
    <h1 class="headline">Hello! My name is
    <span class="highlight">Andrea Maffia.</span>
    I design and develop experiences that make people's lives
    <span class="highlight">just a little bit prettier</span>
    </h1>
</div>

<div class="button-container">
  <%= link_to 'View My Work', pages_portfolio_path, class:"button is-link is-inverted is-large" %>
</div>